### ISSUE TITLE
TODO: Authentication

### ISSUE THREAD

**Issue by h0rzn** [h0rzn/metawatch-agent#20]
- [ ] Generate Default User
- [ ] Connect Users to Authentication
- [ ] Test User Endpoints
